name: marvelwiki
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

